// <auto-generated />
namespace Modulverwaltungssoftware.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class ECTS_sind_jetzt_double_Wert : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ECTS_sind_jetzt_double_Wert));
        
        string IMigrationMetadata.Id
        {
            get { return "202601190905466_ECTS_sind_jetzt_double_Wert"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
